name: tp0
networks:
  testing_net:
    ipam:
      config:
        - subnet: 172.25.125.0/24
      driver: default
services:
  server:
    container_name: server
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    image: server:latest
    networks:
      - testing_net
    volumes:
      - ./server/config.ini:/config.ini

  validator:
    container_name: validator
    image: ubuntu:latest
    networks:
      - testing_net
    volumes:
      - ./validar-echo-server.sh:/validar-echo-server.sh
    command: sh /validar-echo-server.sh
    entrypoint: /bin/bash -c "apt-get update && apt-get install -y netcat-openbsd && sh /validar-echo-server.sh"
